import type { FlowStepItem } from '@shared/components'
import type { ProjectFinanceData } from '@modules/loans/types/projectFinance.types'

export const PROJECT_FINANCE_STEPS: FlowStepItem[] = [
  { stepNumber: 1, title: 'Applicant & Project', shortLabel: 'Applicant & Project' },
  { stepNumber: 2, title: 'Location, Land & Technical', shortLabel: 'Location & Technical' },
  { stepNumber: 3, title: 'Cost & Financing', shortLabel: 'Cost & Financing' },
  { stepNumber: 4, title: 'Market & Financials', shortLabel: 'Market & Financials' },
  { stepNumber: 5, title: 'Loan Requirement & Repayment', shortLabel: 'Loan Requirement' },
  { stepNumber: 6, title: 'Security & Compliance', shortLabel: 'Security & Compliance' },
  { stepNumber: 7, title: 'Documents, Review & Submit', shortLabel: 'Review & Submit' },
]

export const INITIAL_PROJECT_FINANCE_DATA: ProjectFinanceData = {
  applicantName: '',
  entityType: '',
  pan: '',
  cinLlpin: '',
  dateOfIncorporation: '',
  isExistingCustomer: false,
  isExistingBankCustomer: false,
  bankingRelationship: '',
  primaryBusinessActivity: '',
  officeAddressLine1: '',
  officeAddressLine2: '',
  officeState: '',
  officeDistrictCity: '',
  officePinCode: '',
  promoters: [],
  projectName: '',
  projectSector: '',
  projectSubSector: '',
  projectType: '',
  developmentOption: '',
  addressLine1: '',
  addressLine2: '',
  state: '',
  districtCity: '',
  pinCode: '',

  // Step 2 Initial Values
  step2ProjectAddress: '',
  step2State: '',
  step2District: '',
  step2PinCode: '',
  step2ProjectZone: '',
  step2NearestTownCity: '',
  step2DistanceNearestTownKm: '',

  totalLandRequiredAcres: '',
  landAvailableAcres: '',
  landAcquiredAcres: '',
  landPendingAcres: '',
  landOwnership: '',
  landUse: '',
  titleStatus: '',
  encumbrance: '',
  naConversionStatus: '',

  landParcels: [
    {
      id: '1',
      surveyPlotNumber: '',
      areaAcres: '',
      ownership: '',
      acquisitionStatus: '',
      titleStatus: '',
      encumbrance: '',
    },
  ],

  rowRequired: true,
  rowType: '',
  rowTotalLengthKm: '',
  rowObtainedPending: '',
  rowApprovalStatus: '',
  rowExpectedCompletionDate: '',

  powerSource: '',
  waterSource: '',
  approachRoad: '',
  drainageArrangement: '',
  wasteEffluentArrangement: '',
  otherInfrastructure: '',

  // Section 6: Technical Details
  technologyType: '',
  technologyDescription: '',
  technologySource: '',
  technologyProvider: '',
  isTechnologyProven: true,
  isTechnologyLicenseRequired: true,
  technicalConsultant: '',

  // Section 7: Capacity & Production
  proposedCapacity: '',
  capacityUnit: '',
  expectedInitialUtilisationPercent: '',
  stabilisedUtilisationPercent: '',
  productionPerYear: '',
  operatingDaysPerYear: '',
  numberOfShifts: '',

  // Section 8: Plant & Machinery
  plantMachineryList: [
    {
      id: '1',
      machineryName: '',
      category: '',
      manufacturerSupplier: '',
      quantity: '',
      unitCost: '',
      totalCost: '',
    },
  ],

  // Section 9: Raw Material / Inputs
  rawMaterialList: [
    {
      id: '1',
      mainRawMaterial: '',
      source: '',
      supplier: '',
      annualRequirement: '',
      unit: '',
      hasSupplyAgreement: false,
    },
  ],

  // Section 10: EPC / Project Execution
  epcContractor: '',
  contractType: '',
  epcContractValue: '',
  epcAwardDate: '',
  constructionStartDate: '',
  expectedCompletionDate: '',

  // Section 11: Implementation Milestones
  implementationMilestones: [
    {
      id: '1',
      milestone: '',
      plannedDate: '',
      actualDate: '',
      status: 'Planned',
    },
  ],

  // Section 12: Manpower
  totalEmployees: '',
  skilledEmployees: '',
  semiSkilledEmployees: '',
  unskilledEmployees: '',
  technicalStaffEmployees: '',
  administrativeStaffEmployees: '',

  // Step 3: Cost & Funding Details
  landSiteDevCost: '',
  civilWorksCost: '',
  plantMachineryCost: '',
  engineeringTechnicalCost: '',
  preliminaryPreOperativeCost: '',
  marginMoneyWorkingCapitalCost: '',
  contingencyProvisionCost: '',
  totalEstimatedProjectCost: '',

  promotersEquityContribution: '',
  debtTermLoanRequested: '',
  subordinatedDebtUnsecuredLoans: '',
  govtSubsidyCapitalGrant: '',
  proposedDebtToEquityRatio: '',
  proposedLendersLeadBank: '',

  phase1DrawdownInvestment: '',
  phase1Milestone: '',
  phase2DrawdownInvestment: '',
  phase2Milestone: '',
  expectedCommercialOperationsDate: '',

  // Step 4: Market & Financials
  productsServicesList: [],
  targetMarket: '',
  marketType: '',
  targetGeography: '',
  customerSegment: '',
  expectedMarketSharePercent: '',
  majorCompetitors: '',
  competitiveAdvantage: '',
  customersOfftakersList: [],

  projectionPeriodYears: '',
  historicalYears: '',
  projectedYears: '',
  commercialOperationDate: '',
  stabilisationYear: '',

  historicalRevenueFy3: '',
  historicalRevenueFy2: '',
  historicalRevenueFy1: '',
  historicalEbitdaFy3: '',
  historicalEbitdaFy2: '',
  historicalEbitdaFy1: '',
  historicalPatFy3: '',
  historicalPatFy2: '',
  historicalPatFy1: '',
  historicalDebtFy3: '',
  historicalDebtFy2: '',
  historicalDebtFy1: '',

  inventoryDays: '',
  receivableDays: '',
  payableDays: '',
  operatingCycleDays: '',

  // Step 5: Loan Requirement & Repayment
  loanRequirementTotalCost: '',
  loanRequirementOwnContribution: '',
  loanRequiredAmount: '',
  loanType: '',
  schemeProduct: '',
  preferredLender: '',
  proposedDisbursementDate: '',

  repaymentPeriodYears: '',
  moratoriumPeriodMonths: '',
  repaymentFrequency: '',
  expectedInterestRatePercent: '',
  repaymentStartDate: '',
  preferredEmiInstalment: '',

  primaryRepaymentSource: '',
  secondaryRepaymentSource: '',
  dscrProjected: '',
  explainRepaymentSources: '',

  // Step 6: Security & Compliance
  securityList: [],
  typeOfSecurity: '',
  securityAssetDescription: '',
  securityEstimatedValue: '',
  securityOwnershipType: '',
  securityLocationOfAsset: '',
  securityValuationReportAvailable: true,
  securityExistingCharge: false,
  securityExistingChargeDetails: '',

  approvalEnvironmentalClearance: false,
  approvalBuildingPlan: false,
  approvalFactoryLicense: false,
  approvalPollutionControlBoard: false,
  approvalLandUseConversion: false,
  approvalPowerConnection: false,
  approvalWaterSupply: false,
  approvalOther: false,
  approvalOtherSpecify: '',

  businessRegistrationType: '',
  complianceRegistrationNumber: '',
  gstApplicable: true,
  complianceGstNumber: '',
  complianceIncomeTaxPan: '',
  complianceTan: '',

  typeOfInsurance: '',
  insuranceCoverageAmount: '',
  insurancePolicyValidity: '',

  labourLawCompliance: true,
  localAuthorityApprovals: true,
  healthSafetyCompliance: true,
  industrySpecificCompliance: true,
  anyPendingLitigation: false,
  pendingLitigationDetails: '',

  totalProjectCost: '',
  debtFundingRequired: '',
  equityContribution: '',
  preferredFinanceType: '',
  repaymentTenure: '',
  promoterEntityName: '',
  promoterConstitution: '',
  promoterPan: '',
  promoterCibilScore: '',
  promoterNetWorth: '',
  priorProjectExperience: '',
  collateralType: '',
  collateralDescription: '',
  disbursementBankName: '',
  disbursementAccountNumber: '',
  disbursementIfscCode: '',
  uploadedDocs: {},
  declarationAccurateInfo: false,
  declarationAuthorizeVerification: false,
  termsAccepted: false,
}
